# Generated by manual migration to rename underlying table
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('client', '0002_remove_business_owner_business_code_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "business_business" RENAME TO "client_client";',
                    reverse_sql='ALTER TABLE "client_client" RENAME TO "business_business";',
                ),
            ],
            state_operations=[
                migrations.AlterModelTable(
                    name='client',
                    table='client_client',
                ),
            ],
        )
    ]
