# Generated by Django 5.2.7 on 2025-11-06 17:28

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    # No-op: 0001_initial already reflects the desired schema (no owner, has code, autoslug on slug)
    operations = []
