# Generated by Django 5.2.7 on 2025-11-07 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_rename_business_to_client_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table=None,
        ),
    ]
